# Generated by Django 4.1.13 on 2025-04-21 00:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name_plural": "Countries",
            },
        ),
        migrations.CreateModel(
            name="ScholarshipApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("application_id", models.CharField(max_length=20, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Under Review", "Under Review"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("student_mobile", models.CharField(max_length=20)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "passport_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "address_line1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_line2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                ("country", models.CharField(max_length=100)),
                (
                    "nationality",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "highest_education",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "institution_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("graduation_year", models.IntegerField(blank=True, null=True)),
                ("gpa", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "program_type",
                    models.CharField(
                        choices=[
                            ("Undergraduate", "Undergraduate"),
                            ("Graduate", "Graduate"),
                            ("PhD", "PhD"),
                            ("Other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "first_preference",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "second_preference",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "father_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "father_occupation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "father_mobile",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "mother_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "mother_occupation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "mother_mobile",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("documents", models.JSONField(blank=True, null=True)),
                ("student_declaration", models.BooleanField(default=False)),
                ("parent_declaration", models.BooleanField(default=False)),
                (
                    "submitted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cities",
                        to="api.country",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Cities",
                "unique_together": {("name", "country")},
            },
        ),
    ]
